version: 0.0
os: linux
files:
  - source: ./test.txt
    destination: /home/ubuntu/test
hooks:
  AfterInstall:
   - location: ./scripts/setup.sh
     timeout: 300
     runas: root
  ApplicationStart:
  - location: ./scripts/run.sh
    timeout: 400
    runas: root   
